# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf7d7dd0d97e3caa5df0c77b22a1c2f16be71abe4d37be6254a950d761cef3c6b2ae2680674c60c8c7b4d8ef9e1ff4babc20b86992cf9cd06e80258562492267

test:
  secret_key_base: 1ed5edbc9b61805489fc298814aa3f51b1a873904bf7c321d0054deeeb9cebaae29d3d9d7fc5c0ea6a2d1de5ff0bd635b116afe63729cfe609f82b2b9c77452e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
